import React, { useState } from 'react';
import { Card } from './Card';
import type { FruitEspState } from '../types';

interface LoaderCardProps {
  fruitEspState: FruitEspState;
  autoLevelEnabled: boolean;
  targetLevel: number;
  levelingMethod: string;
}

const LOADER_URL = "https://raw.githubusercontent.com/moninhashi-byte/Acrylic-GUI-Lite-modifed-/main/main.luau";

export const LoaderCard: React.FC<LoaderCardProps> = ({
  fruitEspState,
  autoLevelEnabled,
  targetLevel,
  levelingMethod,
}) => {
  const [copyButtonText, setCopyButtonText] = useState('Copy Script');

  const generateConfigScript = (): string => {
    const fruitList = Object.entries(fruitEspState.fruits)
      .filter(([, isEnabled]) => isEnabled)
      .map(([fruitName]) => `        ["${fruitName}"] = true`)
      .join(',\n');

    const configTable = `
-- Generated by Acrylic GUI Lite (modifed) Web UI
getgenv().ACRYLIC_CONFIG = {
    fruitEsp = {
        masterEnabled = ${fruitEspState.masterEnabled},
        fruits = {
${fruitList}
        }
    },
    autoLevel = {
        enabled = ${autoLevelEnabled},
        targetLevel = ${targetLevel},
        method = '${levelingMethod}'
    }
}

-- Load and run the main script
loadstring(game:HttpGet("${LOADER_URL}"))()
`;
    return configTable.trim();
  };


  const handleCopy = () => {
    const script = generateConfigScript();
    navigator.clipboard.writeText(script).then(() => {
      setCopyButtonText('Copied!');
      setTimeout(() => {
        setCopyButtonText('Copy Script');
      }, 2000);
    }).catch(err => {
      console.error('Failed to copy text: ', err);
    });
  };

  return (
    <Card title="Export Configuration">
      <p className="text-sm text-slate-400 mb-4">
        Your settings are configured. Copy the full script below and run it in your executor to apply them in-game.
      </p>
      <div className="bg-slate-900 rounded-md p-3 flex flex-col items-stretch font-mono text-sm overflow-hidden">
        <pre className="text-cyan-300 overflow-x-auto whitespace-pre-wrap scrollbar-hide text-xs leading-relaxed">
          <code>
            {generateConfigScript()}
          </code>
        </pre>
        <button
          onClick={handleCopy}
          aria-label="Copy configuration script"
          className={`mt-4 w-full px-3 py-2 rounded-md text-sm font-semibold transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-slate-900 ${
            copyButtonText === 'Copied!'
              ? 'bg-green-500 text-white'
              : 'bg-cyan-500 hover:bg-cyan-600 text-white'
          }`}
        >
          {copyButtonText}
        </button>
      </div>
    </Card>
  );
};
